spring.application.name=SwapSmart

# Removed spring profiles local line because now hosting on AWS

# Database Connection info
# Using Session Pool on Supabase
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# Below line makes sure table is made if it doesn't exist
spring.jpa.hibernate.ddl-auto=update

# Supabase User Auth
supabase.jwt.secret=${SUPABASE_JWT_SECRET}
supabase.url=${SUPABASE_URL}

# Backend is reached by any network device
server.address=0.0.0.0

# Temporarily disabling Spring Security for now
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
